# Generated by Django 3.1.5 on 2022-01-10 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default=True, max_length=50, null=True)),
                ('last_name', models.CharField(default=True, max_length=50, null=True)),
                ('email', models.EmailField(default=True, max_length=254, null=True)),
                ('password', models.CharField(default=True, max_length=500, null=True)),
                ('cnic', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_picture.png', null=True, upload_to='')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
