# Generated by Django 3.1.5 on 2022-01-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20220110_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
