# Generated by Django 3.1.5 on 2022-01-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20220118_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture.png', null=True, upload_to='static/images/'),
        ),
    ]
