# Generated by Django 3.1.5 on 2022-01-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20220123_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture.png', null=True, upload_to=''),
        ),
    ]
