# Generated by Django 3.1.5 on 2022-01-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20220124_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
