# Generated by Django 3.1.5 on 2022-01-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_remove_employee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture_path',
            field=models.ImageField(blank=True, default='profile_picture.png', null=True, upload_to=''),
        ),
    ]
