# Generated by Django 4.0.1 on 2022-02-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaks',
            name='end',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='breaks',
            name='start',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
