# Generated by Django 4.0.1 on 2022-02-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20220121_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='last_increment_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='last_salary_release_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
