# Generated by Django 3.1.5 on 2022-01-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20220121_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='in_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='out_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
